version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/client/angular
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(frontend)

  - package-ecosystem: pip
    directory: /apps/server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(backend)
