"""convert_timestamps_to_timezone_aware

Revision ID: 251128711576
Revises: 0bfd40fe481c
Create Date: 2026-05-30 00:39:37.440981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy.vector  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "251128711576"
down_revision: Union[str, Sequence[str], None] = "0bfd40fe481c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "diet_tags",
        "tag_name",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "diet_tags",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_diet_tags_name"), table_name="diet_tags")
    op.drop_index(op.f("idx_diet_tags_recipe_id"), table_name="diet_tags")
    op.create_index(
        op.f("ix_diet_tags_recipe_id"), "diet_tags", ["recipe_id"], unique=False
    )
    op.create_index(
        op.f("ix_diet_tags_tag_name"), "diet_tags", ["tag_name"], unique=False
    )
    op.alter_column(
        "ingredient_categories",
        "category_name",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "ingredient_categories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_ingredient_categories_name"), table_name="ingredient_categories"
    )
    op.create_index(
        op.f("ix_ingredient_categories_category_name"),
        "ingredient_categories",
        ["category_name"],
        unique=False,
    )
    op.alter_column(
        "recipe_ingredients",
        "ingredient_name",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "recipe_ingredients",
        "quantity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("1.0"),
    )
    op.alter_column(
        "recipe_ingredients",
        "unit",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    op.alter_column(
        "recipe_ingredients",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        nullable=False,
    )
    op.alter_column(
        "recipe_ingredients",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_recipe_ingredients_ingredient_name"), table_name="recipe_ingredients"
    )
    op.drop_index(
        op.f("idx_recipe_ingredients_recipe_id"), table_name="recipe_ingredients"
    )
    op.create_index(
        op.f("ix_recipe_ingredients_ingredient_name"),
        "recipe_ingredients",
        ["ingredient_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipe_ingredients_recipe_id"),
        "recipe_ingredients",
        ["recipe_id"],
        unique=False,
    )
    op.alter_column(
        "recipes",
        "title",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "recipes",
        "servings",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("4"),
    )
    op.alter_column(
        "recipes",
        "duration_minutes",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "recipes",
        "difficulty",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
        existing_server_default=sa.text("'medium'::text"),
    )
    op.alter_column(
        "recipes",
        "spice_level",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("2"),
    )
    op.alter_column(
        "recipes",
        "origin",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
        existing_server_default=sa.text("'Unknown'::text"),
    )
    op.alter_column(
        "recipes",
        "is_public",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "recipes",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=False,
    )
    op.alter_column(
        "recipes",
        "raw_source",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "recipes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "recipes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_recipes_difficulty"), table_name="recipes")
    op.drop_index(op.f("idx_recipes_duration"), table_name="recipes")
    op.drop_index(op.f("idx_recipes_spice_level"), table_name="recipes")
    op.drop_index(op.f("idx_recipes_user_id"), table_name="recipes")
    op.drop_index(
        op.f("idx_recipes_only_public"),
        table_name="recipes",
        postgresql_where="(is_public = true)",
    )
    op.create_index(
        "idx_recipes_only_public",
        "recipes",
        ["is_public"],
        unique=False,
        postgresql_where=sa.text("is_public = TRUE"),
    )
    op.create_index(
        op.f("ix_recipes_difficulty"), "recipes", ["difficulty"], unique=False
    )
    op.create_index(
        op.f("ix_recipes_duration_minutes"),
        "recipes",
        ["duration_minutes"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipes_spice_level"), "recipes", ["spice_level"], unique=False
    )
    op.create_index(op.f("ix_recipes_user_id"), "recipes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recipes_user_id"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_spice_level"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_duration_minutes"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_difficulty"), table_name="recipes")
    op.drop_index(
        "idx_recipes_only_public",
        table_name="recipes",
        postgresql_where=sa.text("is_public = TRUE"),
    )
    op.create_index(
        op.f("idx_recipes_only_public"),
        "recipes",
        ["id"],
        unique=False,
        postgresql_where="(is_public = true)",
    )
    op.create_index(op.f("idx_recipes_user_id"), "recipes", ["user_id"], unique=False)
    op.create_index(
        op.f("idx_recipes_spice_level"), "recipes", ["spice_level"], unique=False
    )
    op.create_index(
        op.f("idx_recipes_duration"), "recipes", ["duration_minutes"], unique=False
    )
    op.create_index(
        op.f("idx_recipes_difficulty"), "recipes", ["difficulty"], unique=False
    )
    op.alter_column(
        "recipes",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "recipes",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "recipes",
        "raw_source",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "recipes",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=True,
    )
    op.alter_column(
        "recipes",
        "is_public",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "recipes",
        "origin",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("'Unknown'::text"),
    )
    op.alter_column(
        "recipes",
        "spice_level",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("2"),
    )
    op.alter_column(
        "recipes",
        "difficulty",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("'medium'::text"),
    )
    op.alter_column(
        "recipes",
        "duration_minutes",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "recipes",
        "servings",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("4"),
    )
    op.alter_column(
        "recipes",
        "title",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_recipe_ingredients_recipe_id"), table_name="recipe_ingredients"
    )
    op.drop_index(
        op.f("ix_recipe_ingredients_ingredient_name"), table_name="recipe_ingredients"
    )
    op.create_index(
        op.f("idx_recipe_ingredients_recipe_id"),
        "recipe_ingredients",
        ["recipe_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_recipe_ingredients_ingredient_name"),
        "recipe_ingredients",
        ["ingredient_name"],
        unique=False,
    )
    op.alter_column(
        "recipe_ingredients",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "recipe_ingredients",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        nullable=True,
    )
    op.alter_column(
        "recipe_ingredients",
        "unit",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("''::text"),
    )
    op.alter_column(
        "recipe_ingredients",
        "quantity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("1.0"),
    )
    op.alter_column(
        "recipe_ingredients",
        "ingredient_name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_ingredient_categories_category_name"),
        table_name="ingredient_categories",
    )
    op.create_index(
        op.f("idx_ingredient_categories_name"),
        "ingredient_categories",
        ["category_name"],
        unique=False,
    )
    op.alter_column(
        "ingredient_categories",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ingredient_categories",
        "category_name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_diet_tags_tag_name"), table_name="diet_tags")
    op.drop_index(op.f("ix_diet_tags_recipe_id"), table_name="diet_tags")
    op.create_index(
        op.f("idx_diet_tags_recipe_id"), "diet_tags", ["recipe_id"], unique=False
    )
    op.create_index(op.f("idx_diet_tags_name"), "diet_tags", ["tag_name"], unique=False)
    op.alter_column(
        "diet_tags",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "diet_tags",
        "tag_name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
