"""centroid_relationship

Revision ID: 5bc8aad03f38
Revises: 72d66ff5587e
Create Date: 2026-05-30 10:12:52.046458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy.vector # type: ignore


# revision identifiers, used by Alembic.
revision: str = '5bc8aad03f38'
down_revision: Union[str, Sequence[str], None] = '72d66ff5587e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_categories', sa.Column('centroid_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_ingredient_categories_centroid_id'), 'ingredient_categories', ['centroid_id'], unique=False)
    op.create_foreign_key('fk_ingredient_categories_centroid_id_recipe_ingredients', 'ingredient_categories', 'recipe_ingredients', ['centroid_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ingredient_categories_centroid_id_recipe_ingredients', 'ingredient_categories', type_='foreignkey')
    op.drop_index(op.f('ix_ingredient_categories_centroid_id'), table_name='ingredient_categories')
    op.drop_column('ingredient_categories', 'centroid_id')
    # ### end Alembic commands ###
