"""normalized_ingredient_name

Revision ID: 6574e342312b
Revises: 5bc8aad03f38
Create Date: 2026-05-30 23:40:23.912475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy.vector  # type: ignore


# revision identifiers, used by Alembic.
revision: str = "6574e342312b"
down_revision: Union[str, Sequence[str], None] = "5bc8aad03f38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe_ingredients",
        sa.Column("normalized_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column(
        "recipe_ingredients",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_recipe_ingredients_normalized_name"),
        "recipe_ingredients",
        ["normalized_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recipe_ingredients_normalized_name"), table_name="recipe_ingredients"
    )
    op.alter_column(
        "recipe_ingredients",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        existing_nullable=False,
    )
    op.drop_column("recipe_ingredients", "normalized_name")
    # ### end Alembic commands ###
